<a href="https://colab.research.google.com/github/suuu004/Data_analysis/blob/week7/0427_week7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 7주차 과제 2310297 **박이수**

**과제 1**

두 CSV 파일 모두 사용하기

In [ ]:
import pandas as pd
df1 = pd.read_csv("/content/subway_congestion01.csv", encoding="cp949")
df2 = pd.read_csv("/content/subway_congestion02.csv", encoding="cp949")
print(df1.shape)
print(df1.head())
print(df2.shape)
print(df2.head())

(1671, 44)
  요일구분   호선  역번호  출발역 상하구분  5시30분  6시00분  6시30분  7시00분  7시30분  ...  20시00분  \
0   평일  1호선  150  서울역   상선    8.2   21.8   22.3   39.4   67.2  ...    19.7
1   평일  1호선  150  서울역   하선   11.5   11.3   16.9   24.5   40.0  ...    40.0
2   평일  1호선  151   시청   상선    7.8   15.1   18.7   31.0   50.8  ...    23.7
3   평일  1호선  151   시청   하선    9.7   10.4   17.7   22.7   37.3  ...    35.7
4   평일  1호선  152   종각   상선    7.3   12.2   11.5   20.3   29.2  ...    31.6

   20시30분  21시00분  21시30분  22시00분  22시30분  23시00분  23시30분  00시00분  00시30분
0    18.5    18.6    17.1    17.0    17.6    13.0    11.9     6.9     1.1
1    37.9    40.1    36.8    39.2    30.0    18.1    15.9     9.4     0.0
2    22.7    23.2    20.1    21.0    20.6    17.2    13.5     7.2     1.0
3    34.8    39.4    29.7    34.8    25.9    15.8    13.9     6.5     0.4
4    30.1    32.0    25.2    28.0    27.1    23.1    15.8     8.2     1.0

[5 rows x 44 columns]
(1671, 44)
  요일구분   호선  역번호  출발역 상하구분  5시30분  6시00분  6시30분  7시00분  7시30분  ...  20시00분  \
0   평일  1호선  150  서울역   상선    8.3   20.8   21.3   37.4   65.8  ...    19.3
1   평일  1호선  150  서울역   하선   10.5   11.2   16.7   22.9   38.6  ...    39.2
2   평일  1호선  151   시청   상선    6.9   15.4   18.1   29.4   49.1  ...    23.1
3   평일  1호선  151   시청   하선    8.5   10.4   16.6   21.7   36.9  ...    35.2
4   평일  1호선  152   종각   상선    6.3   13.5   11.1   19.3   28.0  ...    30.9

   20시30분  21시00분  21시30분  22시00분  22시30분  23시00분  23시30분  00시00분  00시30분
0    18.3    19.1    15.6    16.1    17.4    14.5     8.6     5.6     1.4
1    37.9    41.2    37.0    38.7    28.4    17.4    11.3     8.4     0.0
2    22.7    23.8    18.8    20.3    20.9    17.4     9.9     6.8     1.5
3    34.8    39.7    30.4    34.2    24.2    15.2    10.0     5.5     0.3
4    29.7    32.8    24.8    27.0    27.0    23.6    12.3     7.7     1.4

[5 rows x 44 columns]

[실행 결과]

각 csv 파일들을 읽고, df1와 df2의 내용을 확인할 수 있다.

**과제 2**

관심 있는 역 2개를 선택, 평일 데이터 사용

-> 시청, 서울역 선택함

In [ ]:
# df1, df2 합치기
df = pd.concat([df1, df2])

# 시청, 서울역 선택

target1 = df[(df["출발역"] == "시청") & (df['요일구분']=="평일")]
small1 = target1[["호선", "출발역","상하구분","8시00분","18시00분"]]
print(small1.head())

target2 = df[(df["출발역"] == "서울역") & (df['요일구분']=="평일")]
small2 = target2[["호선", "출발역","상하구분","8시00분","18시00분"]]
print(small2.head())

     호선 출발역 상하구분  8시00분  18시00분
2   1호선  시청   상선   59.7    64.5
3   1호선  시청   하선   36.2   111.4
86  2호선  시청   내선   95.8    65.5
87  2호선  시청   외선   45.0   110.8
2   1호선  시청   상선   58.7    64.9
      호선  출발역 상하구분  8시00분  18시00분
0    1호선  서울역   상선   76.4    49.2
1    1호선  서울역   하선   41.9   125.6
230  4호선  서울역   상선   58.5    58.2
231  4호선  서울역   하선   31.1    55.5
0    1호선  서울역   상선   72.3    49.0

[실행 결과]

처음에 불러온 두 csv 파일을 합치고, 지정한 출발역이 시청과 서울역인 정보들이 각각 출력되는 것을 확인할 수 있다.

**과제 3**

관심 2개 시간대 평균 혼잡도 비교(예: 8시 00분 & 18시 00분)

In [ ]:
weekday = df[df['요일구분'] == '평일']
station_mean = weekday.groupby('출발역')[['8시00분','18시00분']].mean() # 역별, 8시 18시 혼잡도 구분
display(station_mean)

           8시00분   18시00분
출발역
가락시장     67.7625   63.125
가산디지털단지  67.9250   92.000
강남       74.4250  106.675
강남구청     65.3500   86.350
강동       84.2500   45.450
...          ...      ...
홍제       72.1750   63.275
화곡       63.7750   46.750
화랑대      22.4750   15.225
회현       44.5000   70.400
효창공원앞    50.1500   70.000

[245 rows x 2 columns]

[실행 결과]

groupby를 통해 각 역별로 시간별 혼잡도가 구분되어 출력되는 것을 확인할 수 있고, 그 평균 혼잡도를 알 수 있다.

**과제 4**

결과를 출력하고 CSV 파일로 저장하기

In [ ]:
top10 = station_mean.sort_values('8시00분', ascending=False).head(10)
display(top10) # 혼잡도 순으로 내림차순 정리

result = top10.reset_index()
result.to_csv('top_station_8am.csv', index=False, encoding= 'cp949') # csv로 파일 변환
display(result)

        8시00분   18시00분
출발역
송파    116.925  108.450
석촌    108.350  114.775
문래    101.800   80.625
당산     97.825   77.525
아차산    95.375   71.375
남태령    95.175   88.475
강동구청   93.875   84.300
몽촌토성   92.600   94.350
이수     90.075   68.300
문정     89.975  103.975

    출발역    8시00분   18시00분
0    송파  116.925  108.450
1    석촌  108.350  114.775
2    문래  101.800   80.625
3    당산   97.825   77.525
4   아차산   95.375   71.375
5   남태령   95.175   88.475
6  강동구청   93.875   84.300
7  몽촌토성   92.600   94.350
8    이수   90.075   68.300
9    문정   89.975  103.975

**과제 5**

마지막에 한줄 해석 덧붙이기

[한 줄 해석]

몇몇 역을 제외하면, 대부분 오전 8시가 18시일떄 보다 혼잡도가 높은 것을 확인할 수 있다.